#!/bin/bash
export PS1='\[\033[01;32m\]\u@\h \[\033[01;33m\]\W\[\033[00m\]\$ '
export PATH=~/bin:~/.cabal/bin:$PATH:~/.platformio/penv/bin:~/.local/bin
export LS_COLORS='ow=01;36;40'
export VISUAL=nvim
export EDITOR=nvim
alias vi=nvim
alias ls="ls --color"

[ -z "$TMUX"  ] && { tmux attach || exec tmux new-session && exit;}

pass() { 
  if [[ $@ == "commit" ]]; then 
    command echo hi; 
  else 
    command pass "$@"; 
  fi; 
}

